name: Api-client Package

on:
  push:
    branches: ['staging/api-client','dist/api-client']

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Declare git vars
        id: git_vars
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "hash=$(echo $GITHUB_SHA | cut -c1-5)" >> $GITHUB_OUTPUT
          #echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.hash }}"
