name: Api-client Package

on:
  push:
    branches: ['staging/api-client']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: echo "test"
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})"
